### ISSUE TITLE
能加入有自動選字的注音輸入法嗎?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [hungte/jscin#11]
```
能加入有自動選字的注音輸入法嗎?

chromebook的新酷音輸入法好難用!!

無法自動出現字, 要一個一個選......太奇怪了!







```

Original issue reported on code.google.com by `jian01...@gmail.com` on 27 Sep 2013 at 6:57

**Comment by GoogleCodeExporter** [comment]
```
Chromebook 的內建注音類輸入法已由新酷音 (<=R28) 改為 Google 
Input Tools (>R29)
你的 ChromeOS 用的是哪一版的？
若是新的 (>r29) 可能是剛好遇到有 bug 的版本
bug 可到 chromium 的 issue page 上去 report

jscin 
的目標是提供內建輸入法之外的支援，所以自動選字輸入法��
�較傾向直接修正內建的。
```

Original comment by `hungte@chromium.org` on 29 Sep 2013 at 1:25

**Comment by GoogleCodeExporter** [comment]
Original comment by `hun...@google.com` on 30 Sep 2013 at 5:52
* Added labels: **Priority-Low**
* Removed labels: **Priority-High**, **Performance**

**Comment by GoogleCodeExporter** [comment]
```
... 不過後來因為在實驗 Nacl 的可行性，就順便作了 libchewing 
(新酷音) 的 porting。
使用上比較麻煩，要先裝 jscin 再裝 jscin-chewing 共兩個 
extension，再手動加入 jscin-chewing 裡的 CIN table。

不幸的是由於 webstore 的問題，現在沒辦法發佈新版...
想玩的人可以自己 build 最新版 (need Nacl SDK)。



```

Original comment by `hun...@google.com` on 3 Oct 2013 at 10:34
* Changed state: **Fixed**

Attachments:
* [libchewing.png](https://storage.googleapis.com/google-code-attachments/jscin/issue-11/comment-3/libchewing.png)

**Comment by GoogleCodeExporter** [comment]
```
謝謝您 真是感謝
但目前我在Chrome的Webstore已找不到jsCin輸入法了耶

能post一下連結嗎?

感激不盡
```

Original comment by `jian01...@gmail.com` on 3 Oct 2013 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
如上面說的，目前 webstore 有問題
```

Original comment by `hun...@google.com` on 4 Oct 2013 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
webstore 好了。Jscin 用搜的或是首頁的link就可以安裝。

新酷音模組仍在測試中，可從 
https://chrome.google.com/webstore/detail/dahmmcmnhjgjdappbbmaiempnpmfbdbm 
安裝

裝好後目前不會自動出現在 jscin 裡，要去 jscin table 
手動加入 chewing ，選 url 加入
 chrome-extension://dahmmcmnhjgjdappbbmaiempnpmfbdbm/jscin/chewing.cin
```

Original comment by `hun...@google.com` on 5 Oct 2013 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
謝謝. 太好了

馬上來試試. 感謝.
```

Original comment by `jian01...@gmail.com` on 5 Oct 2013 at 3:54

**Comment by GoogleCodeExporter** [comment]
```
再次感謝！！
終於可以使用到正常的選字注音法了

祝福您 事事順利
```

Original comment by `jian01...@gmail.com` on 5 Oct 2013 at 10:19

**Comment by AndyChiu** [comment]
現在好像又不行了，能否再上架 jscin-chewing？還是要怎麼才能用許氏鍵盤呢？
